"""empty message

Revision ID: 0b04b293096e
Revises: 9ec0dd95de25
Create Date: 2025-05-18 09:12:01.867298

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0b04b293096e'
down_revision = '9ec0dd95de25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    with op.batch_alter_table('rental_contract', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.INTEGER(),
               comment='0：待支付，1：支付成功，2：取消订单,3：撤销订单',
               existing_comment='0：待支付，1：支付成功，2：取消订单',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental_contract', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.INTEGER(),
               comment='0：待支付，1：支付成功，2：取消订单',
               existing_comment='0：待支付，1：支付成功，2：取消订单,3：撤销订单',
               existing_nullable=False)

    op.create_table('order',
    sa.Column('order_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100), nullable=False, comment='写在用户租赁历史中，用户可对租赁状态进行修改，注意：只能归还'),
    sa.Column('house_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('time', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100), nullable=False, comment='租赁时间，按月算，需要前端或者后端计算时间(是否超出日期)'),
    sa.Column('status', mysql.INTEGER(), autoincrement=False, nullable=False, comment='与house_status中的status对应,这里0:归还,1:租赁中\r\n注意：这里修改要影响house_status，那里修改不会影响这里'),
    sa.PrimaryKeyConstraint('order_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    # ### end Alembic commands ###
