"""empty message

Revision ID: 322f2850eff8
Revises: 34bc7ac19b9b
Create Date: 2025-06-01 10:08:50.598624

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '322f2850eff8'
down_revision = '34bc7ac19b9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('house_details_text_snapshot', sa.Text(), nullable=True, comment='房屋坐落、权属、面积、户型、装修及车位等基本情况描述 (合同快照)'))
        batch_op.add_column(sa.Column('deposit_amount_numeric_snapshot', sa.Numeric(precision=10, scale=2), nullable=True, comment='押金金额数字快照 (合同记录)'))
        batch_op.alter_column('handover_checklist_details_text',
               existing_type=mysql.TEXT(),
               comment='房屋交割单详细内容或数据 (合同记录)',
               existing_comment='房屋交割单详细内容或数据 (例如JSON格式，合同记录)',
               existing_nullable=True)
        batch_op.drop_constraint('fk_contractinfo_house_snapshot', type_='foreignkey')
        batch_op.drop_column('fees_borne_by_landlord_text')
        batch_op.drop_column('contact_info_change_notice_days')
        batch_op.drop_column('tenant_return_delay_penalty_terms')
        batch_op.drop_column('house_layout_details_snapshot')
        batch_op.drop_column('rent_free_period_details')
        batch_op.drop_column('renewal_notice_days')
        batch_op.drop_column('tenant_late_payment_penalty_standard')
        batch_op.drop_column('confidentiality_clause_details')
        batch_op.drop_column('house_mortgage_info_snapshot')
        batch_op.drop_column('house_area_sqm_snapshot')
        batch_op.drop_column('landlord_repossess_on_return_overdue_terms')
        batch_op.drop_column('contract_copies_for_landlord')
        batch_op.drop_column('rent_payment_terms_details')
        batch_op.drop_column('sublet_terms_text')
        batch_op.drop_column('contract_copies_for_tenant')
        batch_op.drop_column('contract_total_copies')
        batch_op.drop_column('maintenance_terms')
        batch_op.drop_column('garage_rent_info')
        batch_op.drop_column('house_location_text_snapshot')
        batch_op.drop_column('force_majeure_proof_days')
        batch_op.drop_column('fees_borne_by_tenant_text')
        batch_op.drop_column('tenant_return_overdue_months_limit_landlord_action')
        batch_op.drop_column('rent_tax_info')
        batch_op.drop_column('rent_overdue_days_for_termination')
        batch_op.drop_column('dispute_resolution_choice_text')
        batch_op.drop_column('garage_info_snapshot')
        batch_op.drop_column('deposit_interest_info')
        batch_op.drop_column('landlord_deposit_return_delay_penalty_standard')
        batch_op.drop_column('early_termination_notice_days_breach')
        batch_op.drop_column('deposit_replenish_days_tenant')
        batch_op.drop_column('sale_preemption_notice_days')
        batch_op.drop_column('house_owner_details_snapshot')
        batch_op.drop_column('decoration_permission_terms')
        batch_op.drop_column('house_delivery_terms_text')
        batch_op.drop_column('other_termination_conditions_text')
        batch_op.drop_column('house_id_snapshot')
        batch_op.drop_column('landlord_delivery_delay_penalty_standard')
        batch_op.drop_column('landlord_delivery_delay_days_for_termination')
        batch_op.drop_column('early_termination_penalty_standard_breach')
        batch_op.drop_column('tenant_unauthorized_decoration_restore_days')
        batch_op.drop_column('landlord_overdue_fee_handling_text')
        batch_op.drop_column('loss_compensation_scope_terms')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loss_compensation_scope_terms', mysql.TEXT(), nullable=True, comment='损失赔偿额范围约定，如是否含租金 (合同记录)'))
        batch_op.add_column(sa.Column('landlord_overdue_fee_handling_text', mysql.TEXT(), nullable=True, comment='甲方逾期缴纳其费用时乙方的处理方式 (合同记录)'))
        batch_op.add_column(sa.Column('tenant_unauthorized_decoration_restore_days', mysql.INTEGER(), autoincrement=False, nullable=True, comment='乙方擅自装修甲方要求限期恢复天数 (合同记录)'))
        batch_op.add_column(sa.Column('early_termination_penalty_standard_breach', mysql.TEXT(), nullable=True, comment='提前解约违约金标准 (合同记录)'))
        batch_op.add_column(sa.Column('landlord_delivery_delay_days_for_termination', mysql.INTEGER(), autoincrement=False, nullable=True, comment='甲方迟延交付超X日乙方可解约 (合同记录)'))
        batch_op.add_column(sa.Column('landlord_delivery_delay_penalty_standard', mysql.TEXT(), nullable=True, comment='甲方未按约定交房违约标准 (合同记录)'))
        batch_op.add_column(sa.Column('house_id_snapshot', mysql.INTEGER(), autoincrement=False, nullable=True, comment='关联房屋ID (合同签订时快照)'))
        batch_op.add_column(sa.Column('other_termination_conditions_text', mysql.TEXT(), nullable=True, comment='其他合同终止情形说明 (合同记录)'))
        batch_op.add_column(sa.Column('house_delivery_terms_text', mysql.TEXT(), nullable=True, comment='房屋交付具体约定 (合同记录)'))
        batch_op.add_column(sa.Column('decoration_permission_terms', mysql.TEXT(), nullable=True, comment='甲方是否同意乙方装修及具体条款 (合同记录)'))
        batch_op.add_column(sa.Column('house_owner_details_snapshot', mysql.TEXT(), nullable=True, comment='房屋所有权人及甲方权属情况 (合同快照)'))
        batch_op.add_column(sa.Column('sale_preemption_notice_days', mysql.INTEGER(), autoincrement=False, nullable=True, comment='甲方出卖房屋时需提前通知乙方的天数 (合同记录)'))
        batch_op.add_column(sa.Column('deposit_replenish_days_tenant', mysql.INTEGER(), autoincrement=False, nullable=True, comment='押金被抵扣后乙方补足天数 (合同记录)'))
        batch_op.add_column(sa.Column('early_termination_notice_days_breach', mysql.INTEGER(), autoincrement=False, nullable=True, comment='违约方提前解约通知天数 (合同记录)'))
        batch_op.add_column(sa.Column('landlord_deposit_return_delay_penalty_standard', mysql.TEXT(), nullable=True, comment='甲方未按时返还押金/租金违约标准 (合同记录)'))
        batch_op.add_column(sa.Column('deposit_interest_info', mysql.VARCHAR(length=100), nullable=True, comment='押金是否计息及条款 (合同记录)'))
        batch_op.add_column(sa.Column('garage_info_snapshot', mysql.TEXT(), nullable=True, comment='车库/车位配套信息 (合同快照)'))
        batch_op.add_column(sa.Column('dispute_resolution_choice_text', mysql.TEXT(), nullable=True, comment='争议解决方式选择及具体机构名称 (合同记录)'))
        batch_op.add_column(sa.Column('rent_overdue_days_for_termination', mysql.INTEGER(), autoincrement=False, nullable=True, comment='乙方逾期支付租金超X日甲方可解约 (合同记录)'))
        batch_op.add_column(sa.Column('rent_tax_info', mysql.VARCHAR(length=255), nullable=True, comment='税费信息 (如：税费为XXX，租金是否含税)'))
        batch_op.add_column(sa.Column('tenant_return_overdue_months_limit_landlord_action', mysql.INTEGER(), autoincrement=False, nullable=True, comment='乙方逾期返还超X月甲方可处置物品 (合同记录)'))
        batch_op.add_column(sa.Column('fees_borne_by_tenant_text', mysql.TEXT(), nullable=True, comment='乙方承担的其他费用明细 (合同记录)'))
        batch_op.add_column(sa.Column('force_majeure_proof_days', mysql.INTEGER(), autoincrement=False, nullable=True, comment='不可抗力发生后提供证明材料天数 (合同记录)'))
        batch_op.add_column(sa.Column('house_location_text_snapshot', mysql.TEXT(), nullable=True, comment='房屋坐落详细地址 (合同快照)'))
        batch_op.add_column(sa.Column('garage_rent_info', mysql.TEXT(), nullable=True, comment='车库/车位租金详情 (若与房屋分开或有特别约定)'))
        batch_op.add_column(sa.Column('maintenance_terms', mysql.TEXT(), nullable=True, comment='房屋维修责任及条款 (合同记录)'))
        batch_op.add_column(sa.Column('contract_total_copies', mysql.INTEGER(), autoincrement=False, nullable=True, comment='合同总份数 (合同记录)'))
        batch_op.add_column(sa.Column('contract_copies_for_tenant', mysql.INTEGER(), autoincrement=False, nullable=True, comment='乙方持有合同份数 (合同记录)'))
        batch_op.add_column(sa.Column('sublet_terms_text', mysql.TEXT(), nullable=True, comment='转租约定条款 (例如：是否同意，条件，违约责任等)'))
        batch_op.add_column(sa.Column('rent_payment_terms_details', mysql.TEXT(), nullable=True, comment='租金具体支付期限和方式约定 (合同记录)'))
        batch_op.add_column(sa.Column('contract_copies_for_landlord', mysql.INTEGER(), autoincrement=False, nullable=True, comment='甲方持有合同份数 (合同记录)'))
        batch_op.add_column(sa.Column('landlord_repossess_on_return_overdue_terms', mysql.TEXT(), nullable=True, comment='甲方在乙方逾期返还时处置物品的约定 (合同记录)'))
        batch_op.add_column(sa.Column('house_area_sqm_snapshot', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='房屋建筑面积 (平方米，合同快照)'))
        batch_op.add_column(sa.Column('house_mortgage_info_snapshot', mysql.TEXT(), nullable=True, comment='房屋抵押信息 (合同快照)'))
        batch_op.add_column(sa.Column('confidentiality_clause_details', mysql.TEXT(), nullable=True, comment='具体约定的保密信息内容 (合同记录)'))
        batch_op.add_column(sa.Column('tenant_late_payment_penalty_standard', mysql.TEXT(), nullable=True, comment='乙方未按时支付租金/押金/费用违约标准 (合同记录)'))
        batch_op.add_column(sa.Column('renewal_notice_days', mysql.INTEGER(), autoincrement=False, nullable=True, comment='续租需提前通知天数 (合同记录)'))
        batch_op.add_column(sa.Column('rent_free_period_details', mysql.VARCHAR(length=255), nullable=True, comment='免租期详情 (合同记录)'))
        batch_op.add_column(sa.Column('house_layout_details_snapshot', mysql.VARCHAR(length=255), nullable=True, comment='房屋户型、朝向、装修 (合同快照)'))
        batch_op.add_column(sa.Column('tenant_return_delay_penalty_terms', mysql.TEXT(), nullable=True, comment='乙方逾期返还房屋违约金标准及责任 (合同记录)'))
        batch_op.add_column(sa.Column('contact_info_change_notice_days', mysql.INTEGER(), autoincrement=False, nullable=True, comment='联系方式变更后书面通知对方天数 (合同记录)'))
        batch_op.add_column(sa.Column('fees_borne_by_landlord_text', mysql.TEXT(), nullable=True, comment='甲方承担的其他费用明细 (合同记录)'))
        batch_op.create_foreign_key('fk_contractinfo_house_snapshot', 'house_info', ['house_id_snapshot'], ['house_id'], ondelete='SET NULL')
        batch_op.alter_column('handover_checklist_details_text',
               existing_type=mysql.TEXT(),
               comment='房屋交割单详细内容或数据 (例如JSON格式，合同记录)',
               existing_comment='房屋交割单详细内容或数据 (合同记录)',
               existing_nullable=True)
        batch_op.drop_column('deposit_amount_numeric_snapshot')
        batch_op.drop_column('house_details_text_snapshot')

    # ### end Alembic commands ###
