"""Add ContractInfoModel for detailed contract terms

Revision ID: 34bc7ac19b9b
Revises: 3bf9efd9d3b3
Create Date: 2025-05-31 16:08:19.735478

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '34bc7ac19b9b'
down_revision = '3bf9efd9d3b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_info',
    sa.Column('rental_contract_id', sa.Integer(), nullable=False, comment='关联的RentalContract订单号 (主键)'),
    sa.Column('contract_document_id', sa.String(length=50), nullable=True, comment='合同示范文本编号 (如 GF—2025—2614)'),
    sa.Column('house_id_snapshot', sa.Integer(), nullable=True, comment='关联房屋ID (合同签订时快照)'),
    sa.Column('house_location_text_snapshot', sa.Text(), nullable=True, comment='房屋坐落详细地址 (合同快照)'),
    sa.Column('house_owner_details_snapshot', sa.Text(), nullable=True, comment='房屋所有权人及甲方权属情况 (合同快照)'),
    sa.Column('house_area_sqm_snapshot', sa.Numeric(precision=10, scale=2), nullable=True, comment='房屋建筑面积 (平方米，合同快照)'),
    sa.Column('house_mortgage_info_snapshot', sa.Text(), nullable=True, comment='房屋抵押信息 (合同快照)'),
    sa.Column('house_layout_details_snapshot', sa.String(length=255), nullable=True, comment='房屋户型、朝向、装修 (合同快照)'),
    sa.Column('garage_info_snapshot', sa.Text(), nullable=True, comment='车库/车位配套信息 (合同快照)'),
    sa.Column('lease_purpose_text', sa.Text(), nullable=True, comment='租赁用途 (合同约定)'),
    sa.Column('sublet_terms_text', sa.Text(), nullable=True, comment='转租约定条款 (例如：是否同意，条件，违约责任等)'),
    sa.Column('rent_monthly_amount_text', sa.String(length=255), nullable=True, comment='月租金大写 (合同记录)'),
    sa.Column('rent_tax_info', sa.String(length=255), nullable=True, comment='税费信息 (如：税费为XXX，租金是否含税)'),
    sa.Column('rent_free_period_details', sa.String(length=255), nullable=True, comment='免租期详情 (合同记录)'),
    sa.Column('renewal_notice_days', sa.Integer(), nullable=True, comment='续租需提前通知天数 (合同记录)'),
    sa.Column('rent_payment_frequency', sa.String(length=50), nullable=True, comment='租金支付频率 (合同记录)'),
    sa.Column('rent_payment_terms_details', sa.Text(), nullable=True, comment='租金具体支付期限和方式约定 (合同记录)'),
    sa.Column('landlord_bank_account_info', sa.Text(), nullable=True, comment='甲方收款账户信息 (合同记录)'),
    sa.Column('garage_rent_info', sa.Text(), nullable=True, comment='车库/车位租金详情 (若与房屋分开或有特别约定)'),
    sa.Column('rent_overdue_days_for_termination', sa.Integer(), nullable=True, comment='乙方逾期支付租金超X日甲方可解约 (合同记录)'),
    sa.Column('deposit_amount_text', sa.String(length=255), nullable=True, comment='押金大写 (合同记录)'),
    sa.Column('deposit_interest_info', sa.String(length=100), nullable=True, comment='押金是否计息及条款 (合同记录)'),
    sa.Column('fees_borne_by_landlord_text', sa.Text(), nullable=True, comment='甲方承担的其他费用明细 (合同记录)'),
    sa.Column('fees_borne_by_tenant_text', sa.Text(), nullable=True, comment='乙方承担的其他费用明细 (合同记录)'),
    sa.Column('landlord_overdue_fee_handling_text', sa.Text(), nullable=True, comment='甲方逾期缴纳其费用时乙方的处理方式 (合同记录)'),
    sa.Column('deposit_replenish_days_tenant', sa.Integer(), nullable=True, comment='押金被抵扣后乙方补足天数 (合同记录)'),
    sa.Column('house_delivery_terms_text', sa.Text(), nullable=True, comment='房屋交付具体约定 (合同记录)'),
    sa.Column('landlord_delivery_delay_days_for_termination', sa.Integer(), nullable=True, comment='甲方迟延交付超X日乙方可解约 (合同记录)'),
    sa.Column('tenant_return_delay_penalty_terms', sa.Text(), nullable=True, comment='乙方逾期返还房屋违约金标准及责任 (合同记录)'),
    sa.Column('decoration_permission_terms', sa.Text(), nullable=True, comment='甲方是否同意乙方装修及具体条款 (合同记录)'),
    sa.Column('maintenance_terms', sa.Text(), nullable=True, comment='房屋维修责任及条款 (合同记录)'),
    sa.Column('sale_preemption_notice_days', sa.Integer(), nullable=True, comment='甲方出卖房屋时需提前通知乙方的天数 (合同记录)'),
    sa.Column('confidentiality_clause_details', sa.Text(), nullable=True, comment='具体约定的保密信息内容 (合同记录)'),
    sa.Column('early_termination_notice_days_breach', sa.Integer(), nullable=True, comment='违约方提前解约通知天数 (合同记录)'),
    sa.Column('early_termination_penalty_standard_breach', sa.Text(), nullable=True, comment='提前解约违约金标准 (合同记录)'),
    sa.Column('landlord_delivery_delay_penalty_standard', sa.Text(), nullable=True, comment='甲方未按约定交房违约标准 (合同记录)'),
    sa.Column('landlord_deposit_return_delay_penalty_standard', sa.Text(), nullable=True, comment='甲方未按时返还押金/租金违约标准 (合同记录)'),
    sa.Column('tenant_return_overdue_months_limit_landlord_action', sa.Integer(), nullable=True, comment='乙方逾期返还超X月甲方可处置物品 (合同记录)'),
    sa.Column('landlord_repossess_on_return_overdue_terms', sa.Text(), nullable=True, comment='甲方在乙方逾期返还时处置物品的约定 (合同记录)'),
    sa.Column('tenant_late_payment_penalty_standard', sa.Text(), nullable=True, comment='乙方未按时支付租金/押金/费用违约标准 (合同记录)'),
    sa.Column('loss_compensation_scope_terms', sa.Text(), nullable=True, comment='损失赔偿额范围约定，如是否含租金 (合同记录)'),
    sa.Column('tenant_unauthorized_decoration_restore_days', sa.Integer(), nullable=True, comment='乙方擅自装修甲方要求限期恢复天数 (合同记录)'),
    sa.Column('other_termination_conditions_text', sa.Text(), nullable=True, comment='其他合同终止情形说明 (合同记录)'),
    sa.Column('force_majeure_proof_days', sa.Integer(), nullable=True, comment='不可抗力发生后提供证明材料天数 (合同记录)'),
    sa.Column('contact_info_change_notice_days', sa.Integer(), nullable=True, comment='联系方式变更后书面通知对方天数 (合同记录)'),
    sa.Column('dispute_resolution_choice_text', sa.Text(), nullable=True, comment='争议解决方式选择及具体机构名称 (合同记录)'),
    sa.Column('contract_total_copies', sa.Integer(), nullable=True, comment='合同总份数 (合同记录)'),
    sa.Column('contract_copies_for_landlord', sa.Integer(), nullable=True, comment='甲方持有合同份数 (合同记录)'),
    sa.Column('contract_copies_for_tenant', sa.Integer(), nullable=True, comment='乙方持有合同份数 (合同记录)'),
    sa.Column('other_agreements_text', sa.Text(), nullable=True, comment='其他约定事项全文 (合同记录)'),
    sa.Column('handover_checklist_details_text', sa.Text(), nullable=True, comment='房屋交割单详细内容或数据 (例如JSON格式，合同记录)'),
    sa.Column('info_created_at', sa.DateTime(), nullable=True),
    sa.Column('info_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['house_id_snapshot'], ['house_info.house_id'], name='fk_contractinfo_house_snapshot', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rental_contract_id'], ['rental_contract.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rental_contract_id')
    )
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'login', ['receiver'], ['username'])
        batch_op.create_foreign_key(None, 'login', ['sender'], ['username'])

    with op.batch_alter_table('house_status', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'landlord', ['landlord_name'], ['landlord_name'])

    with op.batch_alter_table('rental_contract', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment='订单号，主键',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('total_amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='月租金或其他周期性租金总额',
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=mysql.INTEGER(),
               comment='0：待支付/待签署，1：支付成功/已生效，2：已取消, 3：已撤销/作废, 4:已到期, 5:已终止',
               existing_comment='0：待支付，1：支付成功，2：取消订单,3：撤销订单',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental_contract', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.INTEGER(),
               comment='0：待支付，1：支付成功，2：取消订单,3：撤销订单',
               existing_comment='0：待支付/待签署，1：支付成功/已生效，2：已取消, 3：已撤销/作废, 4:已到期, 5:已终止',
               existing_nullable=False)
        batch_op.alter_column('total_amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment=None,
               existing_comment='月租金或其他周期性租金总额',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='订单号，主键',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('house_status', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('contract_info')
    # ### end Alembic commands ###
