"""empty message

Revision ID: 3df32edfa07b
Revises: c360c19f3209
Create Date: 2025-05-22 20:56:59.403374

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3df32edfa07b'
down_revision = 'c360c19f3209'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'house_info', ['house_id'], ['house_id'], ondelete='CASCADE')

    with op.batch_alter_table('house_listing_audit', schema=None) as batch_op:
        batch_op.drop_constraint('house_listing_audit_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'house_status', ['house_id', 'landlord_name'], ['house_id', 'landlord_name'], ondelete='CASCADE')

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_constraint('news_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'house_info', ['house_id'], ['house_id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('private_channel', schema=None) as batch_op:
        batch_op.drop_constraint('private_channel_ibfk_3', type_='foreignkey')
        batch_op.create_foreign_key(None, 'house_info', ['house_id'], ['house_id'], ondelete='CASCADE')

    with op.batch_alter_table('rental_contract', schema=None) as batch_op:
        batch_op.alter_column('channel_id',
               existing_type=mysql.INTEGER(),
               comment='关联的私信频道ID',
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'private_channel', ['channel_id'], ['channel_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental_contract', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('channel_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='关联的私信频道ID',
               existing_nullable=False)

    with op.batch_alter_table('private_channel', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('private_channel_ibfk_3', 'house_info', ['house_id'], ['house_id'])

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('news_ibfk_1', 'house_info', ['house_id'], ['house_id'], onupdate='RESTRICT', ondelete='RESTRICT')

    with op.batch_alter_table('house_listing_audit', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('house_listing_audit_ibfk_2', 'house_status', ['house_id', 'landlord_name'], ['house_id', 'landlord_name'])

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
