"""empty message

Revision ID: 4764adb3bb70
Revises: 516a2c1dcb0e
Create Date: 2025-05-07 09:32:44.485488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4764adb3bb70'
down_revision = '516a2c1dcb0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, comment='处理状态：待处理/处理中/已解决/已关闭'))
        batch_op.add_column(sa.Column('handler_username', sa.String(length=100), nullable=True, comment='处理人用户名'))
        batch_op.add_column(sa.Column('last_updated_time', sa.DateTime(), nullable=False, comment='最后更新时间'))
        batch_op.create_foreign_key(None, 'login', ['handler_username'], ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('last_updated_time')
        batch_op.drop_column('handler_username')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
