"""empty message

Revision ID: 4feccf77d326
Revises: 5d8912d25147
Create Date: 2025-05-05 12:53:54.077422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4feccf77d326'
down_revision = '5d8912d25147'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('private_channel',
    sa.Column('channel_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_username', sa.String(length=100), nullable=False, comment='租客用户名'),
    sa.Column('landlord_username', sa.String(length=100), nullable=False, comment='房东用户名'),
    sa.Column('house_id', sa.Integer(), nullable=False, comment='关联的房屋ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='频道创建时间'),
    sa.ForeignKeyConstraint(['house_id'], ['house_info.house_id'], ),
    sa.ForeignKeyConstraint(['landlord_username'], ['login.username'], ),
    sa.ForeignKeyConstraint(['tenant_username'], ['login.username'], ),
    sa.PrimaryKeyConstraint('channel_id'),
    sa.UniqueConstraint('tenant_username', 'landlord_username', 'house_id', name='uq_tenant_landlord_house')
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('channel_id', sa.Integer(), nullable=False, comment='所属私信频道的ID'))
        batch_op.create_foreign_key(None, 'private_channel', ['channel_id'], ['channel_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('channel_id')

    op.drop_table('private_channel')
    # ### end Alembic commands ###
