"""empty message

Revision ID: 516a2c1dcb0e
Revises: 4feccf77d326
Create Date: 2025-05-06 18:43:39.787066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '516a2c1dcb0e'
down_revision = '4feccf77d326'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaint',
    sa.Column('complaint_id', sa.Integer(), autoincrement=True, nullable=False, comment='投诉/消息ID'),
    sa.Column('sender', sa.String(length=100), nullable=False, comment='发送人用户名（租客/房东/管理员）'),
    sa.Column('receiver', sa.String(length=100), nullable=True, comment='接收人用户名（为空表示所有管理员可见）'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息/投诉内容'),
    sa.Column('time', sa.DateTime(), nullable=False, comment='发送时间'),
    sa.Column('type', sa.String(length=20), nullable=False, comment='类型：投诉/反馈'),
    sa.PrimaryKeyConstraint('complaint_id')
    )
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_table_comment(
        existing_comment='预约表'
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.create_table_comment(
        '预约表',
        existing_comment=None
    )

    op.drop_table('complaint')
    # ### end Alembic commands ###
