"""empty message

Revision ID: 5d8912d25147
Revises: c493b3dd82e6
Create Date: 2025-05-05 12:35:01.563854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d8912d25147'
down_revision = 'c493b3dd82e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('message_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sender_username', sa.String(length=100), nullable=False, comment='发送者用户名'),
    sa.Column('receiver_username', sa.String(length=100), nullable=False, comment='接收者用户名'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('timestamp', sa.DateTime(), nullable=False, comment='发送时间'),
    sa.Column('is_read', sa.Boolean(), nullable=False, comment='是否已读 (接收者视角)'),
    sa.ForeignKeyConstraint(['receiver_username'], ['login.username'], ),
    sa.ForeignKeyConstraint(['sender_username'], ['login.username'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    # ### end Alembic commands ###
