"""empty message

Revision ID: 6171a3148596
Revises: 
Create Date: 2025-05-15 21:13:56.279555

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6171a3148596'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('house_listing_audit', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'house_status', ['house_id', 'landlord_name'], ['house_id', 'landlord_name'])
        batch_op.drop_table_comment(
        existing_comment='房源上架审核记录表'
    )

    with op.batch_alter_table('house_status', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.INTEGER(),
               comment='0为空置，1为出租中，2为装修中',
               existing_comment='0为空置（上架），1为出租中，2为装修中，4为审核中，5为审核不通过',
               existing_nullable=False)
        batch_op.create_unique_constraint('uq_house_landlord', ['house_id', 'landlord_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('house_status', schema=None) as batch_op:
        batch_op.drop_constraint('uq_house_landlord', type_='unique')
        batch_op.alter_column('status',
               existing_type=mysql.INTEGER(),
               comment='0为空置（上架），1为出租中，2为装修中，4为审核中，5为审核不通过',
               existing_comment='0为空置，1为出租中，2为装修中',
               existing_nullable=False)

    with op.batch_alter_table('house_listing_audit', schema=None) as batch_op:
        batch_op.create_table_comment(
        '房源上架审核记录表',
        existing_comment=None
    )
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
