"""add daily rent rate table

Revision ID: 6357ff6bd267
Revises: dabf1f613c34
Create Date: 2025-05-09 10:41:13.725035

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6357ff6bd267'
down_revision = 'dabf1f613c34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_constraint('appointment_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('appointment_ibfk_3', type_='foreignkey')
        batch_op.drop_constraint('appointment_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'landlord', ['landlord_name'], ['landlord_name'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'house_info', ['house_id'], ['house_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'tenant', ['tenant_name'], ['tenant_name'], ondelete='CASCADE')

    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.drop_constraint('complaint_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'login', ['handler_username'], ['username'])

    with op.batch_alter_table('daily_rent_rate', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='自增ID',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('rent_rate',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment='出租率百分比，如 66.67',
               existing_comment='出租率百分比（如 66.67）',
               existing_nullable=False)
        batch_op.drop_table_comment(
        existing_comment='每日出租率统计表'
    )

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint('message_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('message_ibfk_3', type_='foreignkey')
        batch_op.drop_constraint('message_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'login', ['receiver_username'], ['username'])
        batch_op.create_foreign_key(None, 'login', ['sender_username'], ['username'])
        batch_op.create_foreign_key(None, 'private_channel', ['channel_id'], ['channel_id'], ondelete='CASCADE')

    with op.batch_alter_table('private_channel', schema=None) as batch_op:
        batch_op.drop_constraint('private_channel_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('private_channel_ibfk_3', type_='foreignkey')
        batch_op.drop_constraint('private_channel_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'login', ['landlord_username'], ['username'])
        batch_op.create_foreign_key(None, 'house_info', ['house_id'], ['house_id'])
        batch_op.create_foreign_key(None, 'login', ['tenant_username'], ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('private_channel', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('private_channel_ibfk_2', 'login', ['landlord_username'], ['username'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.create_foreign_key('private_channel_ibfk_3', 'login', ['tenant_username'], ['username'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.create_foreign_key('private_channel_ibfk_1', 'house_info', ['house_id'], ['house_id'], onupdate='RESTRICT', ondelete='RESTRICT')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('message_ibfk_2', 'login', ['sender_username'], ['username'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.create_foreign_key('message_ibfk_3', 'private_channel', ['channel_id'], ['channel_id'], onupdate='RESTRICT', ondelete='CASCADE')
        batch_op.create_foreign_key('message_ibfk_1', 'login', ['receiver_username'], ['username'], onupdate='RESTRICT', ondelete='RESTRICT')

    with op.batch_alter_table('daily_rent_rate', schema=None) as batch_op:
        batch_op.create_table_comment(
        '每日出租率统计表',
        existing_comment=None
    )
        batch_op.alter_column('rent_rate',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment='出租率百分比（如 66.67）',
               existing_comment='出租率百分比，如 66.67',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment='自增ID',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('complaint_ibfk_1', 'login', ['handler_username'], ['username'], onupdate='RESTRICT', ondelete='RESTRICT')

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('appointment_ibfk_2', 'tenant', ['tenant_name'], ['tenant_name'], onupdate='RESTRICT', ondelete='CASCADE')
        batch_op.create_foreign_key('appointment_ibfk_3', 'landlord', ['landlord_name'], ['landlord_name'], onupdate='RESTRICT', ondelete='CASCADE')
        batch_op.create_foreign_key('appointment_ibfk_1', 'house_info', ['house_id'], ['house_id'], onupdate='RESTRICT', ondelete='CASCADE')

    # ### end Alembic commands ###
