"""empty message

Revision ID: 75e8c48b372b
Revises: 
Create Date: 2025-04-15 15:00:14.802682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75e8c48b372b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('order_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_name', sa.String(length=100), nullable=False, comment='写在用户租赁历史中，用户可对租赁状态进行修改，注意：只能归还'),
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.String(length=100), nullable=False, comment='租赁时间，按月算，需要前端或者后端计算时间(是否超出日期)'),
    sa.Column('status', sa.Integer(), nullable=False, comment='与house_status中的status对应,这里0:归还,1:租赁中\r\n注意：这里修改要影响house_status，那里修改不会影响这里'),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('tenant',
    sa.Column('tenant_name', sa.String(length=100), nullable=False, comment='租客用户名'),
    sa.Column('phone', sa.String(length=100), nullable=False, comment='联系方式'),
    sa.Column('addr', sa.String(length=255), nullable=False, comment='用户住址'),
    sa.PrimaryKeyConstraint('tenant_name')
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False, comment='新闻发布时间，注意新闻只能新增，(尽量)不能修改'),
    sa.Column('house_id', sa.Integer(), nullable=False, comment='房屋id，有一个指向house_info的外键'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='新闻标题（如某某房屋出租了）,一般配对房屋状态变化'),
    sa.Column('desc', sa.String(length=255), nullable=True, comment='新闻内容'),
    sa.ForeignKeyConstraint(['house_id'], ['house_info.house_id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news')
    op.drop_table('tenant')
    op.drop_table('order')
    # ### end Alembic commands ###
