"""empty message

Revision ID: 872fa61087a3
Revises: dabf1f613c34
Create Date: 2025-05-07 21:17:44.696984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '872fa61087a3'
down_revision = 'dabf1f613c34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_username_map',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False, comment='用户邮箱'),
    sa.Column('username', sa.String(length=100), nullable=False, comment='关联的用户名'),
    sa.ForeignKeyConstraint(['username'], ['login.username'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'username', name='uq_email_username_map')
    )
    with op.batch_alter_table('email_username_map', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_username_map_email'), ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_username_map', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_username_map_email'))

    op.drop_table('email_username_map')
    # ### end Alembic commands ###
