"""add rental_contract

Revision ID: 9ec0dd95de25
Revises: 6171a3148596
Create Date: 2025-05-17 00:06:31.641408

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9ec0dd95de25'
down_revision = '6171a3148596'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rental_contract',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('landlord_username', sa.String(length=100), nullable=False),
    sa.Column('tenant_username', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False, comment='0：待支付，1：支付成功，2：取消订单'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rental_transaction', schema=None) as batch_op:
        batch_op.drop_index('order_no')

    op.drop_table('rental_transaction')
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_constraint('appointment_ibfk_3', type_='foreignkey')
        batch_op.drop_constraint('appointment_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('appointment_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenant', ['tenant_name'], ['tenant_name'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'landlord', ['landlord_name'], ['landlord_name'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'house_info', ['house_id'], ['house_id'], ondelete='CASCADE')

    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.drop_constraint('complaint_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'login', ['handler_username'], ['username'])

    with op.batch_alter_table('house_listing_audit', schema=None) as batch_op:
        batch_op.drop_constraint('house_listing_audit_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('house_listing_audit_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'house_status', ['house_id', 'landlord_name'], ['house_id', 'landlord_name'])
        batch_op.create_foreign_key(None, 'landlord', ['landlord_name'], ['landlord_name'])

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint('message_ibfk_3', type_='foreignkey')
        batch_op.drop_constraint('message_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('message_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'private_channel', ['channel_id'], ['channel_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'login', ['receiver_username'], ['username'])
        batch_op.create_foreign_key(None, 'login', ['sender_username'], ['username'])

    with op.batch_alter_table('private_channel', schema=None) as batch_op:
        batch_op.drop_constraint('private_channel_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('private_channel_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('private_channel_ibfk_3', type_='foreignkey')
        batch_op.create_foreign_key(None, 'login', ['landlord_username'], ['username'])
        batch_op.create_foreign_key(None, 'login', ['tenant_username'], ['username'])
        batch_op.create_foreign_key(None, 'house_info', ['house_id'], ['house_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('private_channel', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('private_channel_ibfk_3', 'login', ['tenant_username'], ['username'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.create_foreign_key('private_channel_ibfk_1', 'login', ['landlord_username'], ['username'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.create_foreign_key('private_channel_ibfk_2', 'house_info', ['house_id'], ['house_id'], onupdate='RESTRICT', ondelete='RESTRICT')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('message_ibfk_2', 'login', ['sender_username'], ['username'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.create_foreign_key('message_ibfk_1', 'login', ['receiver_username'], ['username'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.create_foreign_key('message_ibfk_3', 'private_channel', ['channel_id'], ['channel_id'], onupdate='RESTRICT', ondelete='CASCADE')

    with op.batch_alter_table('house_listing_audit', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('house_listing_audit_ibfk_2', 'house_status', ['house_id', 'landlord_name'], ['house_id', 'landlord_name'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.create_foreign_key('house_listing_audit_ibfk_1', 'landlord', ['landlord_name'], ['landlord_name'], onupdate='RESTRICT', ondelete='RESTRICT')

    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('complaint_ibfk_1', 'login', ['handler_username'], ['username'], onupdate='RESTRICT', ondelete='RESTRICT')

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('appointment_ibfk_2', 'house_info', ['house_id'], ['house_id'], onupdate='RESTRICT', ondelete='CASCADE')
        batch_op.create_foreign_key('appointment_ibfk_1', 'landlord', ['landlord_name'], ['landlord_name'], onupdate='RESTRICT', ondelete='CASCADE')
        batch_op.create_foreign_key('appointment_ibfk_3', 'tenant', ['tenant_name'], ['tenant_name'], onupdate='RESTRICT', ondelete='CASCADE')

    op.create_table('rental_transaction',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='交易记录主键'),
    sa.Column('order_no', mysql.VARCHAR(length=50), nullable=False, comment='订单编号'),
    sa.Column('house_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='关联房源ID'),
    sa.Column('landlord_name', mysql.VARCHAR(length=100), nullable=False, comment='房东用户名'),
    sa.Column('tenant_name', mysql.VARCHAR(length=100), nullable=False, comment='租客用户名'),
    sa.Column('start_date', sa.DATE(), nullable=False, comment='租房起始日期'),
    sa.Column('end_date', sa.DATE(), nullable=False, comment='租房结束日期'),
    sa.Column('total_amount', mysql.DECIMAL(precision=10, scale=2), nullable=False, comment='租金总金额'),
    sa.Column('status', mysql.TINYINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='订单状态：0=待支付，1=支付成功，2=取消订单'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='订单创建时间'),
    sa.Column('paid_at', mysql.DATETIME(), nullable=True, comment='支付时间'),
    sa.Column('remark', mysql.TEXT(), nullable=True, comment='备注（可选）'),
    sa.ForeignKeyConstraint(['house_id'], ['house_info.house_id'], name='fk_rental_transaction_house', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='租房交易记录表',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='租房交易记录表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('rental_transaction', schema=None) as batch_op:
        batch_op.create_index('order_no', ['order_no'], unique=True)

    op.drop_table('rental_contract')
    # ### end Alembic commands ###
