"""empty message

Revision ID: a13638c5c4d9
Revises: b471b319a774
Create Date: 2025-06-01 16:38:01.298142

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a13638c5c4d9'
down_revision = 'b471b319a774'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visit_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.Column('unique_visits', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rental_contract', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.INTEGER(),
               comment='0：待签署, 1：已签署待支付, 2：已取消, 3：已撤销, 4：已支付/合同生效, 5：已到期, 6: 已终止/已归还',
               existing_comment='0：待支付/待签署，1：支付成功/已生效，2：已取消, 3：已撤销/作废, 4:已到期, 5:已终止',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental_contract', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.INTEGER(),
               comment='0：待支付/待签署，1：支付成功/已生效，2：已取消, 3：已撤销/作废, 4:已到期, 5:已终止',
               existing_comment='0：待签署, 1：已签署待支付, 2：已取消, 3：已撤销, 4：已支付/合同生效, 5：已到期, 6: 已终止/已归还',
               existing_nullable=False)

    op.drop_table('visit_stats')
    # ### end Alembic commands ###
