"""empty message

Revision ID: b471b319a774
Revises: 322f2850eff8
Create Date: 2025-06-01 10:36:35.369680

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b471b319a774'
down_revision = '322f2850eff8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('landlord_signature_identifier', sa.String(length=255), nullable=True, comment='甲方签名标识 (如用户名或图片URL)'))
        batch_op.add_column(sa.Column('landlord_signature_datetime', sa.DateTime(), nullable=True, comment='甲方签名时间'))
        batch_op.add_column(sa.Column('tenant_signature_identifier', sa.String(length=255), nullable=True, comment='乙方签名标识 (如用户名或图片URL)'))
        batch_op.add_column(sa.Column('tenant_signature_datetime', sa.DateTime(), nullable=True, comment='乙方签名时间'))
        batch_op.add_column(sa.Column('landlord_handover_signature_identifier', sa.String(length=255), nullable=True, comment='交割单甲方签名标识'))
        batch_op.add_column(sa.Column('landlord_handover_signature_datetime', sa.DateTime(), nullable=True, comment='交割单甲方签名时间'))
        batch_op.add_column(sa.Column('tenant_handover_signature_identifier', sa.String(length=255), nullable=True, comment='交割单乙方签名标识'))
        batch_op.add_column(sa.Column('tenant_handover_signature_datetime', sa.DateTime(), nullable=True, comment='交割单乙方签名时间'))
        batch_op.drop_column('deposit_amount_text')
        batch_op.drop_column('rent_monthly_amount_text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rent_monthly_amount_text', mysql.VARCHAR(length=255), nullable=True, comment='月租金大写 (合同记录)'))
        batch_op.add_column(sa.Column('deposit_amount_text', mysql.VARCHAR(length=255), nullable=True, comment='押金大写 (合同记录)'))
        batch_op.drop_column('tenant_handover_signature_datetime')
        batch_op.drop_column('tenant_handover_signature_identifier')
        batch_op.drop_column('landlord_handover_signature_datetime')
        batch_op.drop_column('landlord_handover_signature_identifier')
        batch_op.drop_column('tenant_signature_datetime')
        batch_op.drop_column('tenant_signature_identifier')
        batch_op.drop_column('landlord_signature_datetime')
        batch_op.drop_column('landlord_signature_identifier')

    # ### end Alembic commands ###
