"""empty message

Revision ID: c493b3dd82e6
Revises: 75e8c48b372b
Create Date: 2025-04-26 17:34:37.012722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c493b3dd82e6'
down_revision = '75e8c48b372b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.DateTime(), nullable=False, comment='留言时间'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('time')

    # ### end Alembic commands ###
