"""empty message

Revision ID: dabf1f613c34
Revises: 4764adb3bb70
Create Date: 2025-05-07 10:06:47.383004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dabf1f613c34'
down_revision = '4764adb3bb70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('update_seen_by_sender', sa.Boolean(), nullable=False, comment='发送者是否已查看最新状态更新'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.drop_column('update_seen_by_sender')

    # ### end Alembic commands ###
