"""empty message

Revision ID: f15712681cad
Revises: 872fa61087a3
Create Date: 2025-05-07 21:19:00.847435

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f15712681cad'
down_revision = '872fa61087a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_email',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False, comment='用户邮箱'),
    sa.Column('username', sa.String(length=100), nullable=False, comment='关联的用户名'),
    sa.ForeignKeyConstraint(['username'], ['login.username'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'username', name='uq_email_username_map')
    )
    with op.batch_alter_table('user_email', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email_email'), ['email'], unique=False)

    with op.batch_alter_table('email_username_map', schema=None) as batch_op:
        batch_op.drop_index('ix_email_username_map_email')
        batch_op.drop_index('uq_email_username_map')

    op.drop_table('email_username_map')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_username_map',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False, comment='用户邮箱'),
    sa.Column('username', mysql.VARCHAR(length=100), nullable=False, comment='关联的用户名'),
    sa.ForeignKeyConstraint(['username'], ['login.username'], name='email_username_map_ibfk_1', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('email_username_map', schema=None) as batch_op:
        batch_op.create_index('uq_email_username_map', ['email', 'username'], unique=True)
        batch_op.create_index('ix_email_username_map_email', ['email'], unique=False)

    with op.batch_alter_table('user_email', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email_email'))

    op.drop_table('user_email')
    # ### end Alembic commands ###
